version: 0.1

phases:
  install:
    commands:
      - |
        pip install -U pip
  pre_build:
    commands:
      - |
        [ -d .cfn ] || mkdir .cfn
        aws configure set default.region $AWS_REGION
        [ -d .zip ] || mkdir .zip
        cp -rp src/* .zip
        pip install -r requirements.txt -t .zip
  build:
    commands:
      - |
        cd .zip
        zip -r app.zip *
        cd ..
        aws cloudformation package \
          --template-file cfn.yml \
          --s3-bucket $S3_BUCKET \
          --output-template-file .cfn/packaged.yml
        ls -la .cfn/packaged.yml
        ls -la params

artifacts:
  files:
    - .cfn/*
    - params/*
    - .zip/app.zip
  discard-paths: yes
