version: 0.2

env:
  variables:
    app_path: "app/with-smt-alm-sample"

phases:
  install:
    commands:
      - |
        pip install -U pip
  pre_build:
    commands:
      - |
        [ -d .cfn ] || mkdir .cfn
        aws configure set default.region $AWS_REGION
        [ -d .zip ] || mkdir .zip
        cp -rp ${app_path}/src/* .zip
        pip install -r ${app_path}/requirements.txt -t .zip
        cp -rp ${app_path}/params/* .cfn
  build:
    commands:
      - |
        cd .zip
        zip -r app.zip *
        cd ..
        aws cloudformation package \
          --template-file ${app_path}/cfn.yml \
          --s3-bucket $S3_BUCKET \
          --output-template-file .cfn/packaged.yml
        ls -la .cfn/packaged.yml

artifacts:
  files:
    - .cfn/*
    - .zip/app.zip
  discard-paths: yes
