version: 0.2

env:
  variables:
    app_path: "app/with-smt-alm-sample"

phases:
  install:
    commands:
      - |
        pip install -U pip
  pre_build:
    commands:
      - |
        aws configure set default.region $AWS_REGION
  build:
    commands:
      - |
        [ -d .zip ] || mkdir .zip
        cp -rp ${app_path}/src/* .zip
        pip install -r ${app_path}/requirements.txt -t .zip
        cd .zip
        ls -la

artifacts:
  files:
    - .cfn/*
    - .zip/app.zip
  discard-paths: yes
