version: 0.1

phases:
  install:
    commands:
      - |
        pip install -U pip
  pre_build:
    commands:
      - |
        setenv APP_PATH app/with-smt-alm-sample
        [ -d .cfn ] || mkdir .cfn
        aws configure set default.region $AWS_REGION
        [ -d .zip ] || mkdir .zip
        cp -rp ${APP_PATH}/src/* .zip
        pip install -r ${APP_PATH}/requirements.txt -t .zip
        cp -rp ${APP_PATH}/params/* .cfn
  build:
    commands:
      - |
        setenv APP_PATH app/with-smt-alm-sample
        cd .zip
        zip -r app.zip *
        cd ..
        aws cloudformation package \
          --template-file ${APP_PATH}/cfn.yml \
          --s3-bucket $S3_BUCKET \
          --output-template-file .cfn/packaged.yml
        ls -la .cfn/packaged.yml

artifacts:
  files:
    - .cfn/*
    - .zip/app.zip
  discard-paths: yes
