version: 0.2

env:
  variables:
    app_path: "app/with-smt-alm-sample"

phases:
  install:
    commands:
      - |
        pip install -U pip
  pre_build:
    commands:
      - |
        aws configure set default.region $AWS_REGION
  build:
    commands:
      - |
        echo ${app_path}
        cd ${app_path}
        [ -d .zip ] || mkdir .zip
        cp -rp src/* .zip
        pip install -r requirements.txt -t .zip
        cd .zip
        zip -r app.zip *
        cd ..
        [ -d .cfn ] || mkdir .cfn
        cp -rp params/* .cfn
        aws cloudformation package \
          --template-file cfn.yml \
          --s3-bucket $S3_BUCKET \
          --output-template-file .cfn/packaged.yml
        ls -la .cfn/packaged.yml

artifacts:
  files:
    - .cfn/*
    - .zip/app.zip
  discard-paths: yes
